accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

groups/urls.py
from django.urls import path
from groups import views

app_name = 'groups'

urlpatterns = [
    path('', views.GroupListView.as_view(), name='group_list'),
    path('new/', views.GroupCreateView.as_view(), name='group_form'),
    path('posts/in/<slug>/', views.GroupDetailView.as_view(), name='group_detail'),
    path('join/<slug>/', views.join_group, name='join_group'),
    path('leave/<slug>/', views.leave_group, name='leave_group'),
]

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('new/', views.PostCreateView.as_view(), name='post_form'),
    path('by/<str:username>/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('by/<str:username>', views.PostsByUserView.as_view(), name='posts_by_user'),
]

social_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('home/', views.home, name='home'),
    path('thankyou/', views.thankyou, name='thankyou'),
    path('accounts/', include('accounts.urls')),
    path('groups/', include('groups.urls')),
    path('posts/', include('posts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth import models

# Create your models here.
class User(models.User, models.PermissionsMixin):
    def __str__(self):
        return "@{}".format(self.username) 

groups/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    slug = models.SlugField(max_length=200, unique=True, blank=True, default='')
    members = models.ManyToManyField(User, through=None)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('groups:group_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug= slugify(self.name)
        super(Group, self).save(*args, **kwargs)    

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

from groups.models import Group


User = get_user_model()


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_posts')
    message = models.TextField()
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='posts')
    created_on = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.message

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

groups/forms.py
from django import forms
from groups.models import Group

class GroupForm(forms.ModelForm):
    
    class Meta:
        model = Group
        fields = ('name', 'description',)

posts/forms.py
from django import forms
from posts.models import Post

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ("message", "group")

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from accounts.forms import SignupForm

# Create your views here.
class SignupView(CreateView):
    form_class = SignupForm
    success_url = reverse_lazy('accounts:login')
    template_name = "accounts/signup.html"

groups/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, redirect
from groups.forms import GroupForm
from groups.models import Group

User = get_user_model()

# Create your views here.
class GroupListView(ListView):
    model = Group
    context_object_name = 'groups'
    template_name = 'groups/group_list.html'

class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupForm
    template_name = 'groups/group_form.html'

class GroupDetailView(DetailView):
    model = Group
    template_name = 'groups/group_detail.html'

@login_required
def join_group(request, slug):
    group = get_object_or_404(Group, slug=slug)
    
    if group:
        group.members.add(User.objects.get(id=request.user.id))

    return redirect('groups:group_detail', slug=slug)

@login_required
def leave_group(request, slug):
    group = get_object_or_404(Group, slug=slug)
    
    if group:
        group.members.remove(User.objects.get(id=request.user.id))
        
    return redirect('groups:group_detail', slug=slug)

posts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.models import Post
from posts.forms import PostForm

# Create your views here.
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "posts/post_form.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostCreateView, self).form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('posts:post_detail', kwargs={"username": self.request.user.username, "pk":self.object.id})

class PostDetailView(DetailView):
    model = Post
    template_name = "posts/post_detail.html"

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = "posts/post_delete_confirm.html"
    
    def get_success_url(self):
        return reverse_lazy('posts:post_list')

class PostsByUserView(ListView):
    model = Post
    template_name = "posts/user_posts.html"
    context_object_name = "posts"
    
    def get_queryset(self):
        queryset = super(PostsByUserView, self).get_queryset()
        return queryset.filter(author__username=self.kwargs['username'])

class PostListView(ListView):
    model = Post
    template_name = "posts/post_list.html"
    context_object_name = "posts"
    ordering = ['-created_on']

social_site/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'index.html', {})

@login_required
def home(request):
    return render(request, 'home.html', {})

def thankyou(request):
    return render(request, 'thankyou.html', {})

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <h1>Login</h1>

    <form method="post">
        {% csrf_token %}

        {% bootstrap_form form %}
        
        {% buttons %}
            <button type="submit" class="btn btn-primary">Login</button>
        {% endbuttons %}
    </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'accounts/css/accounts.css' %}">
{% endblock head %}

{% block content %}
    <h1>Sign Up</h1>

    <form method="post">
        {% csrf_token %}

        {% bootstrap_form form %}
        
        {% buttons %}
            <button type="submit" class="btn btn-primary">Sign Up</button>
        {% endbuttons %}
    </form>
{% endblock content %}

groups/templates/groups/group_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ group.name }}</h1>
    <h2>Member Count: {{ group.members.count }}</h2>

    {% if user not in group.members.all %}
        <a class="btn btn-warning btn-lg" href="{% url 'groups:join_group' slug=group.slug %}">Join</a>
    {% else %}
        <a class="btn btn-warning btn-lg" href="{% url 'groups:leave_group' slug=group.slug %}">Leave</a>
    {% endif %}

    {% if not group.posts.all %}
        <h2>No posts in this group yet!</h2>
    {% else %}
        {% for post in group.posts.all %}
            <div class="row">
                <div class="col-md-2">
                    <h3><a href="{% url 'posts:posts_by_user' username=post.author %}">@{{ post.author }}</a></h3>
                </div>

                <div class="col-md-10">
                    <h4>{{ post.author }}</h4>
                    <h3>{{ post.message }}</h3>
                    <p>
                        <a href="{% url 'posts:post_detail' username=post.author pk=post.id %}">{{ post.created_on }}</a>
                        in
                        <a href="{% url 'groups:group_detail' slug=group.slug %}">{{ group.name }}</a>
                    </p>
                </div>
            </div>
            
            <hr>
        {% endfor %}
    {% endif %}
{% endblock content %}

groups/templates/groups/group_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <h1>Create A New Group</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary" type="submit">Create</button>
    </form>
{% endblock content %}

groups/templates/groups/group_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'groups/css/group.css' %}">
{% endblock head %}

{% block content %}
    <div class="row">
        <div class="col-md-5">
            {% if user.is_authenticated %}
                <h2>Welcome back <a href="{% url 'posts:posts_by_user' username=user.username %}">@{{user.username}}</a></h2>
            {% endif %}
            
            <h2>Groups</h2>
            <p>Welcome to the Groups Page!</p>
            <p>Select a Group with a shared interest!</p>

            {% if user.is_authenticated %}
                <a class="btn btn-warning" href="{% url 'groups:group_form' %}">
                    <span class="fa fa-plus"></span> Create New Group!
                </a>
            {% endif %}
        </div>
        
        <div class="col-md-7">
            <ul class="group_list">
                {% if groups %}
                    {% for group in groups %}
                        <li>
                            <a href="{% url 'groups:group_detail' slug=group.slug %}">
                                <div class="group_overview">
                                    <h1>{{ group.name }}</h1>
                                    <p>{{ group.description }}</p>
                                    <div class="row">
                                        <p class="col-md-6">
                                            <span class="badge badge-secondary">{{ group.members.count }}</span>
                                            member{{ group.members.count|pluralize }}
                                        </p>
                                        <p class="col-md-6">
                                            <span class="badge badge-secondary">{{ group.posts.count }}</span>
                                            post{{ group.posts.count|pluralize }}
                                        </p>
                                    </div>
                                    <hr>
                                </div>
                            </a>
                        </li>                    
                    {% endfor %}
                {% else %}
                    <li class="no_groups">No groups available yet!</li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock content %}

posts/templates/posts/post_delete_confirm.html
{% extends 'base.html' %}

{% block content %}
    <h1>Are you sure you want to delete this post?</h1>
    <div class="row">
        <div class="col-md-2">
            <h3><a href="{% url 'posts:posts_by_user' username=post.author %}">@{{ post.author }}</a></h3>
        </div>

        <div class="col-md-10">
            <h4>{{ post.author }}</h4>
            <h3>{{ post.message }}</h3>
            <p>
                <a href="{% url 'posts:post_detail' username=post.author pk=post.id %}">{{ post.created_on }}</a>
                in
                <a href="{% url 'groups:group_detail' slug=post.group.slug %}">{{ post.group.name }}</a>
            </p>

            <form method="post">
                {% csrf_token %}
                <button class="btn btn-danger btn-lg" type="submit">Delete</button>
                <a class="btn btn-default btn-lg" href="{% url 'posts:post_detail' username=post.author pk=post.id %}">Cancel</a>
            </form>
        </div>
    </div>
{% endblock content %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-2">
            <h3><a href="{% url 'posts:posts_by_user' username=post.author %}">@{{ post.author }}</a></h3>
        </div>

        <div class="col-md-10">
            <h4>{{ post.author }}</h4>
            <h3>{{ post.message }}</h3>
            <p>
                <a href="{% url 'posts:post_detail' username=post.author pk=post.id %}">{{ post.created_on }}</a>
                in
                <a href="{% url 'groups:group_detail' slug=post.group.slug %}">{{ post.group.name }}</a>
            </p>

            {% if post.author == user and user.is_authenticated %}
                <a class="btn btn-danger btn-lg" href="{% url 'posts:post_delete' pk=post.id %}"><span class="fa fa-remove"></span>Delete</a>
            {% endif %}
        </div>
    </div>
{% endblock content %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <h2>Create New Post</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary" type="submit">Post</button>
    </form>
{% endblock content %}

posts/templates/posts/post_list.html
{% extends 'base.html' %}

{% block content %}
    <h2>All Posts</h2>
    
    {% if posts %}
        {% for post in posts %}
            <div class="row">
                <div class="col-md-2">
                    <h3><a href="{% url 'posts:posts_by_user' username=post.author %}">@{{ post.author }}</a></h3>
                </div>

                <div class="col-md-10">
                    <h4>{{ post.author }}</h4>
                    <h3>{{ post.message }}</h3>
                    <p>
                        <a href="{% url 'posts:post_detail' username=post.author pk=post.id %}">{{ post.created_on }}</a>
                        in
                        <a href="{% url 'groups:group_detail' slug=post.group.slug %}">{{ post.group.name }}</a>
                    </p>
                </div>
            </div>
            
            <hr>
        {% endfor %}
    {% else %}
        No posts avaiable yet!
    {% endif %}
{% endblock content %}

posts/templates/posts/user_posts.html
{% extends 'base.html' %}

{% block content %}
    <h2>@{{ posts.0.author }}</h2>
    <h3>Post History</h3>
    
    {% if posts %}
        {% for post in posts %}
            <div class="row">
                <div class="col-md-2">
                    <h3><a href="{% url 'posts:posts_by_user' username=post.author %}">@{{ post.author }}</a></h3>
                </div>

                <div class="col-md-10">
                    <h4>{{ post.author }}</h4>
                    <h3>{{ post.message }}</h3>
                    <p>
                        <a href="{% url 'posts:post_detail' username=post.author pk=post.id %}">{{ post.created_on }}</a>
                        in
                        <a href="{% url 'groups:group_detail' slug=post.group.slug %}">{{ post.group.name }}</a>
                    </p>
                </div>
            </div>

            <hr>
        {% endfor %}
    {% else %}
        This user has not posted yet!
    {% endif %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Star Social</title>
    <link rel="icon" type="image/png" href="{% static 'images/favicon.jpg' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'social_site_css/master.css' %}">
    {% block head %}
    {% endblock head %}
</head>
<body>
    <nav class="navbar navbar-inverse navbar-staic-top">
        <div class="container">
            <ul class="nav navbar-nav navbar-header">
                <li><a class="navbar-brand" href="{% url 'index' %}">Star Social</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if not user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'posts:post_list' %}">Posts</a></li>
                    <li><a class="navbar-link" href="{% url 'groups:group_list' %}">Groups</a></li>
                    <li><a class="navbar-link" href="{% url 'accounts:login' %}">Log in</a></li>
                    <li><a class="navbar-link" href="{% url 'accounts:signup' %}">Sign up</a></li>
                {% else %}
                    <li><a class="navbar-link" href="{% url 'posts:post_list' %}">Posts</a></li>
                    <li><a class="navbar-link" href="{% url 'posts:post_form' %}">New Post</a></li>
                    <li><a class="navbar-link" href="{% url 'groups:group_list' %}">Groups</a></li>
                    <li><a class="navbar-link" href="{% url 'groups:group_form' %}">Create Group</a></li>
                    <li><a class="navbar-link" href="{% url 'accounts:logout' %}">Log out</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container content">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>You are now logged in!</h1>
    <h2><a href="{% url 'groups:group_list' %}">Go to Groups</a></h2>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to Star Social!</h1>
{% endblock content %}

templates/thankyou.html
{% extends 'base.html' %}

{% block content %}
    <h1>Thanks for visiting! Come back soon!</h1>
{% endblock content %}